spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: '5672'
    listener:
      simple:
        default-requeue-rejected: 'false'

rabbitmq:
  retry:
    delay-in-ms: 60000
    count: 3
